<a href="https://colab.research.google.com/github/malekebenhassine/hello-world/blob/main/Snippets_Importing_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.

In [ ]:
!pip install matplotlib-venn

In [ ]:
!apt-get -qq install -y libfluidsynth1

# Install 7zip reader [libarchive](https://pypi.python.org/pypi/libarchive)

In [ ]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

# Install GraphViz & [PyDot](https://pypi.python.org/pypi/pydot)

In [ ]:
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

# Install [cartopy](http://scitools.org.uk/cartopy/docs/latest/)

In [ ]:
!pip install cartopy
import cartopy

In [10]:
import pandas as pd

# Essaye d'abord ISO-8859-1 (latin1)
historique = pd.read_csv('/content/datasetcomplet7.csv', encoding='ISO-8859-1', sep=';')

# Ou si ça ne marche pas, essaye cp1252
#historique = pd.read_csv('/content/datasetcomplet7.csv', encoding='cp1252')

# Vérifie les premières lignes
historique.head()


InvoiceNo SellToCustomerNo      ProductNo  ClientID      ProduitID  \
0  FA20/0312         CL000044  SEHDDLEN20101  CL000044  SEHDDLEN20101   
1  FA20/0312         CL000044  SEKITCIS19A01  CL000044  SEKITCIS19A01   
2  FA20/0312         CL000044  SEKITCIS19A04  CL000044  SEKITCIS19A04   
3  FA20/0312         CL000044  SEKITCIS19A05  CL000044  SEKITCIS19A05   
4  FA20/0312         CL000044  SEKITCIS19A06  CL000044  SEKITCIS19A06   

     DateID  StatutID  Montant_initial_TND Quantity  Forfait  Statut_Creance  \
0  20200731       112  Montant_initial_TND        2        0  Montant Ouvert   
1  20200731       113  Montant_initial_TND        2        0  Montant Ouvert   
2  20200731       114  Montant_initial_TND        4        0  Montant Ouvert   
3  20200731       115  Montant_initial_TND        8        0  Montant Ouvert   
4  20200731       116  Montant_initial_TND        8        0  Montant Ouvert   

  Type_Creance  Statut_Documentaire NatureCreance   Source Payment_Method  \
0     Standard  Factureréceptionnée        Normal  FACTURE            VIR   
1     Standard  Factureréceptionnée        Normal  FACTURE            VIR   
2     Standard  Factureréceptionnée        Normal  FACTURE            VIR   
3     Standard  Factureréceptionnée        Normal  FACTURE            VIR   
4     Standard  Factureréceptionnée        Normal  FACTURE            VIR   

  PostingDate_Text DueDate_Text     Alerte_Retard  
0       31/07/2020   29/09/2020  À temps ou léger  
1       31/07/2020   29/09/2020  À temps ou léger  
2       31/07/2020   29/09/2020  À temps ou léger  
3       31/07/2020   29/09/2020  À temps ou léger  
4       31/07/2020   29/09/2020  À temps ou léger

In [11]:
historique.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5803 entries, 0 to 5802
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   InvoiceNo            5803 non-null   object
 1   SellToCustomerNo     5803 non-null   object
 2   ProductNo            5803 non-null   object
 3   ClientID             5803 non-null   object
 4   ProduitID            5803 non-null   object
 5   DateID               5803 non-null   int64 
 6   StatutID             5803 non-null   int64 
 7   Montant_initial_TND  5322 non-null   object
 8   Quantity             5803 non-null   object
 9   Forfait              5803 non-null   int64 
 10  Statut_Creance       5803 non-null   object
 11  Type_Creance         5803 non-null   object
 12  Statut_Documentaire  5803 non-null   object
 13  NatureCreance        5803 non-null   object
 14  Source               5803 non-null   object
 15  Payment_Method       5803 non-null   object
 16  Postin

In [12]:
import pandas as pd
import numpy as np

# 📥 Charger le fichier (tu l’as déjà fait, donc on continue sur 'historique')

# 1️⃣ Conversion des montants et des quantités
historique['Montant_initial_TND'] = pd.to_numeric(historique['Montant_initial_TND'], errors='coerce')
historique['Quantity'] = pd.to_numeric(historique['Quantity'], errors='coerce')

# Vérifie s’il y a des valeurs manquantes après conversion
print(historique[['Montant_initial_TND', 'Quantity']].isnull().sum())

# 2️⃣ Conversion des dates
historique['PostingDate'] = pd.to_datetime(historique['PostingDate_Text'], errors='coerce')
historique['DueDate'] = pd.to_datetime(historique['DueDate_Text'], errors='coerce')

# Vérifie si des dates sont manquantes
print(historique[['PostingDate', 'DueDate']].isnull().sum())

# 3️⃣ Remplacement des valeurs manquantes si nécessaire
# Par exemple : Remplacer Montant manquant par 0 (ou autre stratégie)
historique['Montant_initial_TND'] = historique['Montant_initial_TND'].fillna(0)
historique['Quantity'] = historique['Quantity'].fillna(0)

# 4️⃣ Encodage des variables catégorielles (label encoding pour les premières étapes)
from sklearn.preprocessing import LabelEncoder

colonnes_a_encoder = ['Statut_Creance', 'Type_Creance', 'Statut_Documentaire', 'NatureCreance', 'Source', 'Payment_Method']

# Création d’un dictionnaire pour conserver les encodeurs (utile si besoin plus tard)
encodeurs = {}

for col in colonnes_a_encoder:
    le = LabelEncoder()
    historique[col] = le.fit_transform(historique[col].astype(str))
    encodeurs[col] = le

# 5️⃣ Encodage de la cible Alerte_Retard (si binaire ou multi-classe)
le_target = LabelEncoder()
historique['Alerte_Retard_encoded'] = le_target.fit_transform(historique['Alerte_Retard'].astype(str))

# 6️⃣ Vérification finale
print(historique.head())


Montant_initial_TND    5602
Quantity                 87
dtype: int64
PostingDate      0
DueDate        613
dtype: int64


<ipython-input-12-1a6d3634b50b>:14: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  historique['PostingDate'] = pd.to_datetime(historique['PostingDate_Text'], errors='coerce')
<ipython-input-12-1a6d3634b50b>:15: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  historique['DueDate'] = pd.to_datetime(historique['DueDate_Text'], errors='coerce')


   InvoiceNo SellToCustomerNo      ProductNo  ClientID      ProduitID  \
0  FA20/0312         CL000044  SEHDDLEN20101  CL000044  SEHDDLEN20101   
1  FA20/0312         CL000044  SEKITCIS19A01  CL000044  SEKITCIS19A01   
2  FA20/0312         CL000044  SEKITCIS19A04  CL000044  SEKITCIS19A04   
3  FA20/0312         CL000044  SEKITCIS19A05  CL000044  SEKITCIS19A05   
4  FA20/0312         CL000044  SEKITCIS19A06  CL000044  SEKITCIS19A06   

     DateID  StatutID  Montant_initial_TND  Quantity  Forfait  ...  \
0  20200731       112                  0.0       2.0        0  ...   
1  20200731       113                  0.0       2.0        0  ...   
2  20200731       114                  0.0       4.0        0  ...   
3  20200731       115                  0.0       8.0        0  ...   
4  20200731       116                  0.0       8.0        0  ...   

   Statut_Documentaire  NatureCreance  Source  Payment_Method  \
0                    0              1       1               2   
1         

In [13]:
from sklearn.model_selection import train_test_split

# Définir la variable cible (target)
y = historique['Alerte_Retard_encoded']

# Définir les variables explicatives (features) en excluant la target et les colonnes inutiles
X = historique.drop(columns=['Alerte_Retard', 'Alerte_Retard_encoded', 'PostingDate_Text', 'DueDate_Text', 'PostingDate', 'DueDate', 'InvoiceNo', 'SellToCustomerNo', 'ClientID', 'ProduitID', 'ProductNo'])

# Vérifier la forme des datasets
print('X shape:', X.shape)
print('y shape:', y.shape)

# Diviser en train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print('X_train:', X_train.shape)
print('X_test:', X_test.shape)


X shape: (5803, 11)
y shape: (5803,)
X_train: (4642, 11)
X_test: (1161, 11)


In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialiser le modèle
model = LogisticRegression(max_iter=1000)

# Entraîner le modèle
model.fit(X_train, y_train)

# Prédire sur le jeu de test
y_pred = model.predict(X_test)

# Évaluer la performance
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nMatrice de confusion:\n", confusion_matrix(y_test, y_pred))


Accuracy Score: 0.7424633936261843

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        85
           1       0.00      0.00      0.00        49
           2       0.00      0.00      0.00       165
           3       0.74      1.00      0.85       862

    accuracy                           0.74      1161
   macro avg       0.19      0.25      0.21      1161
weighted avg       0.55      0.74      0.63      1161


Matrice de confusion:
 [[  0   0   0  85]
 [  0   0   0  49]
 [  0   0   0 165]
 [  0   0   0 862]]


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no pre

In [15]:
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nMatrice de confusion:\n", confusion_matrix(y_test, y_pred))



Accuracy Score: 0.1515934539190353

Classification Report:
               precision    recall  f1-score   support

           0       0.08      0.52      0.13        85
           1       0.04      0.39      0.08        49
           2       0.00      0.00      0.00       165
           3       0.86      0.13      0.23       862

    accuracy                           0.15      1161
   macro avg       0.24      0.26      0.11      1161
weighted avg       0.64      0.15      0.18      1161


Matrice de confusion:
 [[ 44  37   1   3]
 [ 26  19   0   4]
 [ 86  67   0  12]
 [426 321   2 113]]


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler

# Initialiser le suréchantillonnage
smote = SMOTE(random_state=42)

# Normaliser les données pour améliorer la convergence (important pour Logistic Regression)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Appliquer SMOTE sur le train
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

# Vérifier la distribution des classes après SMOTE
import collections
print("Distribution après SMOTE :", collections.Counter(y_train_res))

# Réentraîner le modèle
model = LogisticRegression(max_iter=1000)
model.fit(X_train_res, y_train_res)

# Prédictions
y_pred = model.predict(X_test_scaled)

# Évaluation
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nMatrice de confusion:\n", confusion_matrix(y_test, y_pred))


Distribution après SMOTE : Counter({3: 3447, 1: 3447, 0: 3447, 2: 3447})
Accuracy Score: 0.29112833763996554

Classification Report:
               precision    recall  f1-score   support

           0       0.13      0.49      0.21        85
           1       0.04      0.27      0.07        49
           2       0.18      0.29      0.22       165
           3       0.83      0.27      0.41       862

    accuracy                           0.29      1161
   macro avg       0.30      0.33      0.23      1161
weighted avg       0.65      0.29      0.36      1161


Matrice de confusion:
 [[ 42  22  14   7]
 [ 12  13  12  12]
 [ 35  53  48  29]
 [223 213 191 235]]


In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialiser le modèle Random Forest
rf_model = RandomForestClassifier(random_state=42)

# Entraîner le modèle sur les données rééquilibrées
rf_model.fit(X_train_res, y_train_res)

# Prédire sur le jeu de test
y_pred_rf = rf_model.predict(X_test_scaled)

# Évaluer le modèle
print("Accuracy Score:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nMatrice de confusion:\n", confusion_matrix(y_test, y_pred_rf))


Accuracy Score: 0.6623600344530577

Classification Report:
               precision    recall  f1-score   support

           0       0.37      0.48      0.42        85
           1       0.18      0.27      0.22        49
           2       0.32      0.35      0.34       165
           3       0.82      0.76      0.79       862

    accuracy                           0.66      1161
   macro avg       0.42      0.47      0.44      1161
weighted avg       0.69      0.66      0.67      1161


Matrice de confusion:
 [[ 41   7   9  28]
 [  4  13   7  25]
 [ 10   8  58  89]
 [ 55  43 107 657]]


In [24]:
import pandas as pd

# Générer les prédictions sur tout le dataset
historique['Prediction_Retard'] = rf_model.predict(scaler.transform(X))

# Si besoin, générer aussi les probabilités (score de risque)
proba = rf_model.predict_proba(scaler.transform(X))
historique['Probabilité_Retard_Critique'] = proba[:, 3]  # La 4e colonne correspond à la classe "Retard critique"

# Exporter en CSV
historique[['ClientID', 'InvoiceNo','Prediction_Retard', 'Probabilité_Retard_Critique']].to_csv('predictions_finales.csv', index=False)

print("✅ Fichier 'predictions3_finales.csv' créé avec succès.")


✅ Fichier 'predictions3_finales.csv' créé avec succès.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')